// Represents a single trade recorded in the trading journal
export interface Trade {

    // Unique identifier for the trade
    id: number;

    // Trading instrument (e.g., BTC, ETH, SOL)
    asset: string;

    // Trade position type
    direction: "Long" | "Short";

    // Profit or loss generated by the trade
    // Positive = Profit, Negative = Loss
    pnl: number;

    // Date and time when the trade was executed
    createdAt: string;
}